function createfigureR(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 29-May-2018 14:16:14

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');
figuresize( 20 , 17, 'centimeters');
% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'MarkerSize',10,'LineWidth',2);
set(plot1(1),'DisplayName','raios individuais','Marker','v');
set(plot1(2),'DisplayName','raios concatenados','Marker','hexagram');

% Create ylabel
ylabel('Acurácia (%)','FontWeight','bold','FontSize',30);

% Create xlabel
xlabel('n','FontWeight','bold','FontSize',30);
xlim([1 6]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',30,'YGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.456873528785664 0.180605643880169 0.39489490769647 0.129111846748151],...
    'FontSize',22);

